package com.reminder.vo;

public enum RepeatFrequency {
	EVERY_MONDAY("EVERY_MONDAY"),
	EVERY_TUESDAY("EVERY_TUESDAY"),
	EVERY_WEDNESDAY("EVERY_WEDNESDAY"),
	EVERY_THRUSDAY("EVERY_THRUSDAY"),
	EVERY_FRIDAY("EVERY_FRIDAY"),
	EVERY_SATURDAY("EVERY_SATURDAY"),
	EVERY_SUNDAY("EVERY_SUNDAY"),
	EVERY_WEEKDAY("EVERY_WEEKDAY"),
	
	FIRST_MONDAY("FIRST_MONDAY"),
	FIRST_TUESDAY("FIRST_TUESDAY"),
	FIRST_WEDNESDAY("FIRST_WEDNESDAY"),
	FIRST_THRUSDAY("FIRST_THRUSDAY"),
	FIRST_FRIDAY("FIRST_FRIDAY"),
	FIRST_SATURDAY("FIRST_SATURDAY"),
	FIRST_SUNDAY("FIRST_SUNDAY"),
	
	SECOND_MONDAY("SECOND_MONDAY"),
	SECOND_TUESDAY("SECOND_TUESDAY"),
	SECOND_WEDNESDAY("SECOND_WEDNESDAY"),
	SECOND_THRUSDAY("SECOND_THRUSDAY"),
	SECOND_FRIDAY("SECOND_FRIDAY"),
	SECOND_SATURDAY("SECOND_SATURDAY"),
	SECOND_SUNDAY("SECOND_SUNDAY"),
	
	THIRD_MONDAY("THIRD_MONDAY"),
	THIRD_TUESDAY("THIRD_TUESDAY"),
	THIRD_WEDNESDAY("FIRST_WEDNESDAY"),
	THIRD_THRUSDAY("THIRD_WEDNESDAY"),
	THIRD_FRIDAY("THIRD_FRIDAY"),
	THIRD_SATURDAY("THIRD_SATURDAY"),
	THIRD_SUNDAY("THIRD_SUNDAY"),
	
	FOURTH_MONDAY("FOURTH_MONDAY"),
	FOURTH_TUESDAY("FOURTH_TUESDAY"),
	FOURTH_WEDNESDAY("FOURTH_WEDNESDAY"),
	FOURTH_THRUSDAY("FOURTH_THRUSDAY"),
	FOURTH_FRIDAY("FOURTH_FRIDAY"),
	FOURTH_SATURDAY("FOURTH_SATURDAY"),
	FOURTH_SUNDAY("FOURTH_SUNDAY");
	
	private String fequency ;
	private RepeatFrequency(String fequency) {
		this.fequency = fequency;
	}
	public String getFequency() {
		return fequency;
	}
	public void setFequency(String fequency) {
		this.fequency = fequency;
	}
	

}
